package com.uninote.backend.service;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.springframework.stereotype.Service;

@Service
public class PdfContentAnalyzerService {

    private static final Pattern NOISE_PATTERNS = Pattern.compile(
            "(?i)(scanned by|watermark|page \\d+ of \\d+|null|generated by|scanner|ocr|copyright|all rights reserved)"
    );

    private static final int MIN_LENGTH = 5;
    private static final double MIN_ALPHANUMERIC_RATIO = 0.3;
    private static final double MAX_NOISE_RATIO = 0.2;

    public boolean isValidContent(String content) {
        if (content == null) {
            return false;
        }

        content = content.trim();

        if (content.isEmpty() || content.length() < MIN_LENGTH) {
            return false;
        }

        double noiseRatio = calculateNoiseRatio(content);
        if (noiseRatio > MAX_NOISE_RATIO) {
            return false;
        }

        long alphaNumericCount = content.chars().filter(Character::isLetterOrDigit).count();
        if ((double) alphaNumericCount / content.length() < MIN_ALPHANUMERIC_RATIO) {
            return false;
        }

        return true;
    }

    private double calculateNoiseRatio(String content) {
        Matcher matcher = NOISE_PATTERNS.matcher(content);
        int noiseLength = 0;

        while (matcher.find()) {
            noiseLength += matcher.end() - matcher.start();
        }

        return (double) noiseLength / content.length();
    }
}